dist: xenial
language: generic

addons:
  apt:
    packages:
      - net-tools
      - libpcre3-dev
      - build-essential
      - realpath

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.23.2
    - IMAGES_PATH=~/.gojira-images
    - GOJIRA_VERSION=v0.2.0
    - TEST_REPO=kong
    # hack to help gojira deal with custom dirs
    - LUAROCKS=3.1.3
    - OPENRESTY_BASE=1.15.8.1
    - OPENSSL=1.1.1c
  matrix:
    - TEST_FROM=1.2.0
      TEST_TO=fix/upstream_algorithms_schema
      UPATH_TO=1.3.0
      DATABASE=cassandra
    - TEST_FROM=1.2.0
      TEST_TO=fix/upstream_algorithms_schema
      UPATH_TO=1.3.0
      DATABASE=postgres
    - TEST_FROM=0.14.1
      TEST_TO=next
      UPATH_TO=1.2.0
      DATABASE=postgres
    - TEST_FROM=1.0.0
      TEST_TO=next
      UPATH_TO=1.2.0
      DATABASE=postgres
    - TEST_FROM=1.1.0
      TEST_TO=next
      UPATH_TO=1.2.0
      DATABASE=postgres
    - TEST_FROM=0.14.1
      TEST_TO=next
      UPATH_TO=1.2.0
      DATABASE=cassandra
    - TEST_FROM=1.0.0
      TEST_TO=next
      UPATH_TO=1.2.0
      DATABASE=cassandra
    - TEST_FROM=1.1.0
      TEST_TO=next
      UPATH_TO=1.2.0
      DATABASE=cassandra

script:
  - ./test.sh -b $TEST_REPO:$TEST_FROM -t $TEST_REPO:$TEST_TO -d $DATABASE "$TRAVIS_BUILD_DIR/upgrade_paths/${TEST_FROM}_${UPATH_TO-$TEST_TO}/"

after_failure:
  - cat run.log
