dist: xenial
language: generic

addons:
  apt:
    packages:
      - net-tools
      - libpcre3-dev
      - build-essential
      - realpath

services:
  - docker

env:
  global:
    - PATH=$PATH:~/.local/bin
    - DOCKER_COMPOSE_VERSION=1.23.2
    - IMAGES_PATH=~/.gojira-images
    - GOJIRA_VERSION=v0.2.0
    - TEST_REPO=kong
  matrix:
    - TEST_FROM=0.14.1
      TEST_TO=1.1.0
      DATABASE=postgres
    - TEST_FROM=1.0.0
      TEST_TO=1.1.0
      DATABASE=postgres
before_install:
  - pushd $HOME
  - git clone -b $GOJIRA_VERSION https://github.com/kong/kong-gojira.git
  - mkdir -p ~/.local/bin
  - ln -s $HOME/kong-gojira/gojira.sh ~/.local/bin/gojira
  - popd

install:
  - bash .ci/cache.sh load $TEST_REPO:$TEST_FROM $IMAGES_PATH
  - bash .ci/cache.sh load $TEST_REPO:$TEST_TO $IMAGES_PATH

before_cache:
  - bash .ci/cache.sh save $TEST_REPO:$TEST_FROM $IMAGES_PATH
  - bash .ci/cache.sh save $TEST_REPO:$TEST_TO $IMAGES_PATH

script:
  - bash test.sh -b $TEST_REPO:$TEST_FROM -t $TEST_REPO:$TEST_TO -d $DATABASE upgrade_paths/$TEST_FROM-$TEST-TO/

cache:
  apt: true
  pip: true
  directories:
    - $IMAGES_PATH
