dist: xenial
language: generic

addons:
  apt:
    packages:
      - net-tools
      - libpcre3-dev
      - build-essential
      - realpath

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.23.2
    - IMAGES_PATH=~/.gojira-images
    - GOJIRA_VERSION=v0.2.0
    - TEST_REPO=kong
    - TAG_OR_BRANCH_TO=release/1.5.0
    - UPATH_TO=1.4.0
  matrix:
    - TAG_OR_BRANCH_FROM=0.14.1
      DATABASE=postgres
    - TAG_OR_BRANCH_FROM=1.0.0
      DATABASE=postgres
    - TAG_OR_BRANCH_FROM=1.1.0
      DATABASE=postgres
    - TAG_OR_BRANCH_FROM=1.2.0
      DATABASE=postgres
    - TAG_OR_BRANCH_FROM=1.3.0
      DATABASE=postgres
    - TAG_OR_BRANCH_FROM=0.14.1
      DATABASE=cassandra
    - TAG_OR_BRANCH_FROM=1.0.0
      DATABASE=cassandra
    - TAG_OR_BRANCH_FROM=1.1.0
      DATABASE=cassandra
    - TAG_OR_BRANCH_FROM=1.2.0
      DATABASE=cassandra
    - TAG_OR_BRANCH_FROM=1.3.0
      DATABASE=cassandra

script:
  - ./test.sh -b $TEST_REPO:$TAG_OR_BRANCH_FROM -t $TEST_REPO:$TAG_OR_BRANCH_TO -d $DATABASE "$TRAVIS_BUILD_DIR/upgrade_paths/${TAG_OR_BRANCH_FROM}_${UPATH_TO-$TAG_OR_BRANCH_TO}/"
