#!/usr/bin/env bash

MOCKSERVER_PATH=$GOJIRA_PATH/extra/mockserver


mockserver_setup() {
  if [[ ! -d "$GOJIRA_KONG_PATH" ]]; then create_kong; fi

  add_egg $MOCKSERVER_PATH/mockserver-compose.yml.sh

  >&2 echo ""
  >&2 echo "Enabling Mock-Server"
  >&2 echo ""
  >&2 echo "==============================================="
  >&2 echo " * Dashboard:      http://localhost:1080/mockserver/dashboard"
  >&2 echo " * Documentation:  https://www.mock-server.com"
  >&2 echo " *   Expectations: https://www.mock-server.com/mock_server/creating_expectations.html"
  >&2 echo "==============================================="
  >&2 echo ""

  main "$@"
}


mockserver_setup "$@"